version: "3.9"

services:
    postgres:
        image: postgres:16
        container_name: document_dispatch_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: dispatchuser
            POSTGRES_PASSWORD: dispatchpass
            POSTGRES_DB: documentdispatch
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
        postgres_data: